CREATE TABLE IF NOT EXISTS mutations (
	id_mutation VARCHAR(14) PRIMARY KEY,
	numero_mutation SMALLINT,
	date_mutation DATE,
	id_nature_mutation SMALLINT,
	valeur_fonciere REAL    NOT NULL
);

CREATE INDEX ON mutations(date_mutation);


CREATE TABLE IF NOT EXISTS localisations (
	id_adresse VARCHAR(64) PRIMARY KEY,
	code_com VARCHAR(5) references communes(code_com),
	adresse_code_voie VARCHAR(4),
	nom_voie VARCHAR(255),
	numero INTEGER,
	suffixe CHAR(1),
	latitude REAL,
	longitude REAL
);

CREATE INDEX on localisations(code_com);


CREATE TABLE IF NOT EXISTS parcelles (
	id_parcelle VARCHAR(14) PRIMARY KEY,
	ancien_id_parcelle VARCHAR(14),
	code_nature_culture VARCHAR(2) references natures_culture (id_nat_cult),
	code_nature_culture_speciale VARCHAR(5) references natures_culture_speciales (id_nat_cult_spe)
);

CREATE TABLE IF NOT EXISTS parcelles_mutations (
	id_mutation VARCHAR(14) references mutations(id_mutation),
	id_parcelle VARCHAR(14) references parcelles(id_parcelle),
	PRIMARY KEY(id_mutation, id_parcelle)
);

create index on parcelles_mutations(id_parcelle, id_mutation);



CREATE TABLE IF NOT EXISTS locals (
	id_local VARCHAR(64) PRIMARY KEY,
	code_type_local SMALLINT references types_local(id_type_loc),
	id_parcelle VARCHAR(14) references parcelles(id_parcelle),
	surface_batiment INTEGER,
	nombre_piece_principal SMALLINT,
	nb_lots SMALLINT
);

CREATE INDEX on locals(id_parcelle);


CREATE TABLE IF NOT EXISTS lots (
	id_lot INTEGER,
	id_local VARCHAR(64) references locals(id_local),
	lot_surface_carrez REAL,
	PRIMARY KEY(id_lot, id_mutation, id_local)
);


CREATE TABLE IF NOT EXISTS sous_parcelles (
	id_parcelle VARCHAR(255) references parcelles(id_parcelle),
	sous_parcelle INTEGER GENERATED BY DEFAULT AS IDENTITY,
	surface_terrain INTEGER,
	id_adresse VARCHAR(64),
	PRIMARY KEY(id_parcelle, sous_parcelle)
);



