CREATE TABLE IF NOT EXISTS "mutations" (
	"id_mutation" VARCHAR(14) NOT NULL UNIQUE,
	"numero_mutation" SMALLINT,
	"date_mutation" DATE,
	"id_nature_mutation" SMALLINT,
	"valeur_fonciere" REAL NOT NULL,
	PRIMARY KEY("id_mutation", "numero_mutation")
);




CREATE TABLE IF NOT EXISTS "nature_mutation" (
	"id_nature_mutation" SMALLINT NOT NULL UNIQUE,
	"libelle" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_nature_mutation")
);




CREATE TABLE IF NOT EXISTS "parcelles" (
	"id_parcelle" VARCHAR(14) NOT NULL UNIQUE,
	"ancien_id_parcelle" VARCHAR(14),
	"code_nature_culture" VARCHAR(2),
	"code_nature_culture_speciale" VARCHAR(5),
	"latitude" REAL,
	"longitude" REAL,
	PRIMARY KEY("id_parcelle")
);




CREATE TABLE IF NOT EXISTS "parcelle_mutation" (
	"id_mutation" VARCHAR(14) NOT NULL,
	"numero_mutation" SMALLINT NOT NULL,
	"id_parcelle" VARCHAR(14) NOT NULL,
	PRIMARY KEY("id_mutation", "numero_mutation", "id_parcelle")
);




CREATE TABLE IF NOT EXISTS "lot" (
	"id_lot" INTEGER NOT NULL,
	"id_mutation" VARCHAR(14) NOT NULL,
	"id_local" VARCHAR(64) NOT NULL,
	"lot_surface_carrez" REAL,
	PRIMARY KEY("id_lot", "id_mutation", "id_local")
);




CREATE TABLE IF NOT EXISTS "local" (
	"id_local" VARCHAR(64) NOT NULL,
	"code_type_local" SMALLINT,
	"id_parcelle" VARCHAR(14),
	"surface_batiment" INTEGER,
	"nombre_piece_principal" SMALLINT,
	PRIMARY KEY("id_local")
);




CREATE TABLE IF NOT EXISTS "sous_parcelle" (
	"id_parcelle" VARCHAR(255) NOT NULL,
	"sous_parcelle" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"surface_terrain" INTEGER,
	"id_adresse" VARCHAR(64),
	PRIMARY KEY("id_parcelle", "sous_parcelle")
);




CREATE TABLE IF NOT EXISTS "nature_culture" (
	"id_nature_culture" VARCHAR(2) NOT NULL UNIQUE,
	"libelle" VARCHAR(255),
	PRIMARY KEY("id_nature_culture")
);




CREATE TABLE IF NOT EXISTS "nature_culture_special" (
	"id_nature_culture_special" VARCHAR(5) NOT NULL UNIQUE,
	"libelle" VARCHAR(255),
	PRIMARY KEY("id_nature_culture_special")
);




CREATE TABLE IF NOT EXISTS "adresse" (
	"id_adresse" VARCHAR(64) NOT NULL UNIQUE,
	"code_commune" VARCHAR(5),
	"adresse_code_voie" VARCHAR(4),
	"nom_voie" VARCHAR(255),
	"numero" INTEGER,
	"suffixe" CHAR(1),
	PRIMARY KEY("id_adresse")
);




CREATE TABLE IF NOT EXISTS "commune" (
	"code_commune" VARCHAR(5) NOT NULL UNIQUE,
	"code_postal" VARCHAR(255),
	"libelle_commune" VARCHAR(255),
	"ancien_code_commune" VARCHAR(5),
	"ancien_libelle_commune" VARCHAR(255),
	"code_departement" VARCHAR(2),
	PRIMARY KEY("code_commune")
);



ALTER TABLE "mutations"
ADD FOREIGN KEY("id_nature_mutation") REFERENCES "nature_mutation"("id_nature_mutation")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "parcelle_mutation"
ADD FOREIGN KEY("id_parcelle") REFERENCES "parcelles"("id_parcelle")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "parcelle_mutation"
ADD FOREIGN KEY("id_mutation") REFERENCES "mutations"("id_mutation")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "local"
ADD FOREIGN KEY("id_parcelle") REFERENCES "parcelles"("id_parcelle")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "parcelle_mutation"
ADD FOREIGN KEY("numero_mutation") REFERENCES "mutations"("numero_mutation")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sous_parcelle"
ADD FOREIGN KEY("id_parcelle") REFERENCES "parcelles"("id_parcelle")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "nature_culture"
ADD FOREIGN KEY("id_nature_culture") REFERENCES "parcelles"("code_nature_culture")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "nature_culture_special"
ADD FOREIGN KEY("id_nature_culture_special") REFERENCES "parcelles"("code_nature_culture_speciale")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lot"
ADD FOREIGN KEY("id_mutation") REFERENCES "mutations"("id_mutation")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lot"
ADD FOREIGN KEY("id_local") REFERENCES "local"("id_local")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sous_parcelle"
ADD FOREIGN KEY("id_adresse") REFERENCES "adresse"("id_adresse")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "commune"
ADD FOREIGN KEY("code_commune") REFERENCES "adresse"("code_commune")
ON UPDATE NO ACTION ON DELETE NO ACTION;